# Generated by Django 3.2.2 on 2021-06-03 14:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tests', '0005_alter_choice_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChessBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board',
                 django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10),
                                                           size=8)),
            ],
        ),
    ]
